SHUFFLE_BUFFER_SIZE: 1000  # Adjust based on your dataset size/memory
PREFETCH_BUFFER_SIZE: -1   # Use -1 to represent tf.data.AUTOTUNE
CACHE_DATASET: True     
AUGMENTATION:
  rotation_range: 30                # Slightly lower to retain medical image integrity
  width_shift_range: 0.1            # Minor shifts help, but avoid extreme distortions
  height_shift_range: 0.1
  shear_range: 0.1
  zoom_range: 0.1                   # Reduce aggressive zooming
  horizontal_flip: True             # Good for symmetry; okay in most radiology cases
  fill_mode: "nearest"

IMAGE_SIZE: [224, 224, 3]
BATCH_SIZE: 32                      # Increased batch size for more stable gradients
INCLUDE_TOP: False
EPOCHS: 10                         # You can reduce this with EarlyStopping enabled
CLASSES: 4
WEIGHTS: imagenet
LEARNING_RATE: 0.0001              # Slightly lower learning rate for better fine-tuning
DENSE_UNITS: 128                    # For custom top layer
DROPOUT_RATE: 0.5                   # Prevent overfitting
L2_REGULARIZATION: 0.0005          # Weight decay to reduce overfitting
FREEZE_TILL: 150                    # Unfreeze last 150 layers for fine-tuning
EARLY_STOPPING_PATIENCE: 3       # Stop training if no val_loss improvement
REDUCE_LR_PATIENCE: 10
REDUCE_LR_FACTOR: 0.002
USE_COSINE_DECAY: true
COSINE_DECAY_TYPE: "restart"       # options: "restart" or "normal"
FIRST_DECAY_STEPS: 10              # in epochs
T_MULTIPLIER: 2.0
M_MULTIPLIER: 1.0
COSINE_DECAY_ALPHA: 0.1
LABEL_SMOOTHING: 0.1
USE_MIXUP: True
USE_CUTMIX: False
MIXUP_ALPHA: 0.2
CUTMIX_ALPHA: 1.0
CLASS_WEIGHTS: true
USE_CLASS_WEIGHTS: true
