artifacts_root: artifacts 


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1IHyIq7ucik6_HXguHVD_xUKY3dDaJF1K/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion